name: im_avatar
description: A simple to use avatar widget, with support for selecting a new avatar. The avatar can be selected from camera or gallery.
version: 0.1.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

